name: subgo

on:
  schedule: 
    - cron: "*/30 * * * *"
  push:
    branches:
      - master
  watch:
    types: started
    
env:
  TZ: Asia/Shanghai
  
jobs:
  MainWork:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:      
      - name: Set Timezone to UTC+8
        env: 
            DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "$TZ"
 
      - name: Clone Workflow Repository
        uses: actions/checkout@v2

      - name: Get sub thingy
        id: getsub
        run: |
          curl -o index.html https://proxy.tgbot.co/clash/proxies?type=vmess
          echo ::set-output name=status::success
          
      - name: Filter config
        if: steps.getsub.output.status != 'success'
        id: filter
        run: |
          sed -i 's/.*CN_.*//g' index.html
          sed -i 's/.*"type":"ss".*//g' index.html
          sed -i 's/.*"type":"ssr".*//g' index.html
          sed -i 's/.*"type":"trojan".*//g' index.html
          sed -i '/^$/d' index.html
          sed -n '/.*"port":443.*/p' index.html > index2.html
          sed -n '/.*"server":"/([0,1]?\d{1,2}|2([0-4][0-9]|5[0-5]))(\.([0,1]?\d{1,2}|2([0-4][0-9]|5[0-5]))){3}/".*/p' index2.html > index3.html
          echo ::set-output name=status::success
        
      - name: Commit Files
        if: steps.filter.output.status != 'success'
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "更新"
          echo ::set-output name=status::success
          
      # 此处的 ${{ secrets.GITHUB_TOKEN }} 是 Actions 自有变量，不用管
      - name: GitHub Push
        if: steps.commit.output.status != 'success'
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Send Info to Telegram
        if: steps.commit.output.status != 'success'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            订阅清洗完成
