name: subgo

on:
  schedule: 
    - cron: "25 2 * * *"
  push:
    branches:
      - master
  watch:
    types: started
    
env:
  TZ: Asia/Shanghai
  
jobs:
  MainWork:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:      
      - name: Set Timezone to UTC+8
        env: 
            DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "$TZ"
 
      - name: Clone Workflow Repository
        uses: actions/checkout@v2

      - name: Get sub thingy
        id: getsub
        run: |
          curl -o index.html http://tomtop.xyz/clash/proxies?type=vmess
          echo ::set-output name=status::success
