name: subgo

on:
  schedule: 
    - cron: "*/30 * * * *"
  push:
    branches:
      - master
  watch:
    types: started
    
env:
  TZ: Asia/Shanghai
  
jobs:
  MainWork:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:      
      - name: Clone Workflow Repository
        uses: actions/checkout@v2

      - name: Get sub thingy
        id: getsub
        run: |
          curl -o index.html https://proxy.tgbot.co/clash/proxies?type=vmess
          echo ::set-output name=status::success
          
      - name: Filter config
        if: steps.getsub.output.status != 'success'
        id: filter
        run: |
          sed -i 's/.*CN_.*//g' index.html
          sed -i 's/.*ZZ_.*//g' index.html
          sed -i 's/.*"type":"ss".*//g' index.html
          sed -i 's/.*"type":"ssr".*//g' index.html
          sed -i 's/.*"type":"trojan".*//g' index.html
          sed -i 's/.*"network":"tcp".*//g' index.html
          sed -i 's/.*workers.dev//g' index.html
          sed -i '/^$/d' index.html
          sed -n '/.*"port":443,.*/p' index.html > index2.html
          sed -n '/.*"port":80,.*/p' index.html >> index2.html
          sed -rn '/.*((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5]).*/p' index2.html > index3.html
          sed -i 's/"www\.[^ ]*"},/"data.video.qiyi.com"},/g' index3.html
          sed -i 's/"m\.[^ ]*"},/"data.video.qiyi.com"},/g' index3.html
          sed -i 's/"www\.[^ ]*"}/"data.video.qiyi.com"}/g' index3.html
          sed -i 's/"m\.[^ ]*"}/"data.video.qiyi.com"}/g' index3.html
          sed -i 's/{"HOST":"[^ ]*\.xyz"},/{"HOST":"data.video.qiyi.com"},/g' index3.html
          sed -i 's/"servername":"[^ ]*\.xyz"}/"servername":"data.video.qiyi.com"}/g' index3.html
          sed -i 's/{"HOST":"[^ ]*\.top"},/{"HOST":"data.video.qiyi.com"},/g' index3.html
          sed -i 's/"servername":"[^ ]*\.top"}/"servername":"data.video.qiyi.com"}/g' index3.html
          sed -i 's/{"HOST":"[^ ]*\.ml"},/{"HOST":"data.video.qiyi.com"},/g' index3.html
          sed -i 's/"servername":"[^ ]*\.ml"}/"servername":"data.video.qiyi.com"}/g' index3.html
          sed -i 's/{"HOST":"[^ ]*\.tk"},/{"HOST":"data.video.qiyi.com"},/g' index3.html
          sed -i 's/"servername":"[^ ]*\.tk"}/"servername":"data.video.qiyi.com"}/g' index3.html
          sed -i 's/{"HOST":"[^ ]*\.live"},/{"HOST":"data.video.qiyi.com"},/g' index3.html
          sed -i 's/"servername":"[^ ]*\.live"}/"servername":"data.video.qiyi.com"}/g' index3.html
          sed -i 's/{"HOST":"[^ ]*\.cf"},/{"HOST":"data.video.qiyi.com"},/g' index3.html
          sed -i 's/"servername":"[^ ]*\.cf"}/"servername":"data.video.qiyi.com"}/g' index3.html
          sed -i 's/{"HOST":"[^ ]*\.ga"},/{"HOST":"data.video.qiyi.com"},/g' index3.html
          sed -i 's/"servername":"[^ ]*\.ga"}/"servername":"data.video.qiyi.com"}/g' index3.html
          sed -i 's/{"HOST":"[^ ]*\.cn"},/{"HOST":"data.video.qiyi.com"},/g' index3.html
          sed -i 's/"servername":"[^ ]*\.cn"}/"servername":"data.video.qiyi.com"}/g' index3.html
          sed -i 's/{"HOST":"[^ ]*\.tech"},/{"HOST":"data.video.qiyi.com"},/g' index3.html
          sed -i 's/"servername":"[^ ]*\.tech"}/"servername":"data.video.qiyi.com"}/g' index3.html
          sed -i 's/{"HOST":"[^ ]*\.systems"},/{"HOST":"data.video.qiyi.com"},/g' index3.html
          sed -i 's/"servername":"[^ ]*\.systems"}/"servername":"data.video.qiyi.com"}/g' index3.html
          sed -n '/.*data.video.qiyi.com.*/p' index3.html > index4.html
          rm index3.html
          mv index4.html index3.html
          sed -i '1i\proxies:' index3.html
          sed -i '1i\proxies:' index2.html
          echo ::set-output name=status::success
        
      - name: Commit Files
        if: steps.filter.output.status != 'success'
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "更新"
          echo ::set-output name=status::success
           
      - name: Transcribe to QX formant
        run: |
          curl -o indexqx.html 'https://subcon.py6.pw/sub?target=quanx&url=https%3A%2F%2Fraw.githubusercontent.com%2Fsprindjack%2Fsubgotr%2Fmaster%2Findex.html&insert=false&emoji=true&list=true&udp=true&tfo=false&scv=true&fdn=true&sort=true'
          sed -i 's/fast-open=false,/tls-verification=true,\sfast-open=false,/g' indexqx.html
          
      # 此处的 ${{ secrets.GITHUB_TOKEN }} 是 Actions 自有变量，不用管
      - name: GitHub Push
        if: steps.commit.output.status != 'success'
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Send Info to Telegram
        if: steps.commit.output.status != 'success'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            订阅清洗完成
